### ISSUE TITLE
Add description

### ISSUE THREAD

**Issue by MatheusRich** [dry-rb/dry-rails#2]
I know it's a brand new project, but a description of what it does (or intends to) would be nice.

Edit: a roadmap would be good too :smile:

**Comment by solnic** [comment]
I added a one-line description from the gemspec to the README. This is sufficient for now. We have unified README's across all the projects and now we don't have full-blown project descriptions and instead all READMEs include links to documentation where you can find detailed description of a given gem. dry-rails will have its own documentation section in dry-rb.org once I release 0.1.0 (and so currently broken README documentation links won't be broken anymore).

We will *probably* add descriptions and simple code examples to all READMEs under dry-rb once our devtools setup supports it. My idea is to reuse documentation intros in the READMEs, this way we would keep both in sync very easily.

> Edit: a roadmap would be good too

My experience with roadmaps in OSS projects is that they make very little sense due to erratic work efforts. What I've found to be much better is addressing whatever is important at any given moment. Sure, it's nice to have an overview of what you would like to achieve with a project but at the same time it's a trap you set for yourself. With a roadmap, you set people's expectations, and then life happens and you can't deliver what you "promised" and now you feel bad.

Anyhow, that's *my* plan:

- Wrap up `0.1.0` ASAP that will include things that I need
- Talk to people in the community to understand what the needs/expectations are
- Report issues explaining how certain things can be done and mark them as `help wanted`
- See what happens next

I'm kick-starting this project because I think it's important to have a smooth integration with Rails where people can start using dry-rb gems with Rails with close-to-zero effort - that's the goal and a (vague) roadmap 😄
